.Dd June 24, 2026
.Dt REGFEXPORT 1
.Os
.Sh NAME
.Nm regfexport
.Nd exports items stored in a Windows NT Registry File (REGF)
.Sh SYNOPSIS
.Nm regfexport
.Op Fl c Ar codepage
.Op Fl K Ar key_path
.Op Fl l Ar log_file
.Op Fl hvV
.Ar source
.Sh DESCRIPTION
.Nm regfexport
is a utility to export items stored in a Windows NT Registry File (REGF)
.Pp
.Nm regfexport
is part of the
.Nm libregf
package.
.Nm libregf
is a library to access the Windows NT Registry File (REGF) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar codepage
codepage of ASCII strings, options: ascii, windows-874, windows-932, \
windows-936, windows-949, windows-950, windows-1250, windows-1251, windows-1252 \
(default), windows-1253, windows-1254, windows-1255, windows-1256, windows-1257 \
or windows-1258
.It Fl h
shows this help
.It Fl K Ar key_path
show information about a specific key path
.It Fl l Ar log_file
logs information about the exported items
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# cregexport SYSTEM.DAT
cregexport 20260623
.sp
Key path:
Key:
.sp
Key path: SOFTWARE
Key: SOFTWARE
.sp
Key path: SOFTWARE\\Classes
Key: Classes
.sp
Key path: SOFTWARE\\Classes\\CLSID
Key: CLSID
Value: 0 (default)
Type: string (REG_SZ)
Data size: 0
Data:
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh SEE ALSO
.Xr regfinfo 1 ,
.Xr regfmount 1
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libregf/issues
.Sh COPYRIGHT
Copyright (C) 2009-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
